"""empty message

Revision ID: 273a9bac3f45
Revises: f29f0e4bc4f9
Create Date: 2018-01-16 22:31:21.028924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273a9bac3f45'
down_revision = 'f29f0e4bc4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beau_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('beau_esssay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beau_esssay'], ['beauti_essay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beau_comment')
    # ### end Alembic commands ###
