"""empty message

Revision ID: 2f075959b3b2
Revises: 90e7b5f35529
Create Date: 2018-01-16 22:18:20.957615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f075959b3b2'
down_revision = '90e7b5f35529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beauti_essay', sa.Column('praise_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beauti_essay', 'praise_num')
    # ### end Alembic commands ###
