"""empty message

Revision ID: 86c0cca85f59
Revises: 3de54aa67dd9
Create Date: 2018-01-09 11:14:54.674159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c0cca85f59'
down_revision = '3de54aa67dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwd_hash')
    # ### end Alembic commands ###
