"""empty message

Revision ID: 90e7b5f35529
Revises: 8a165b4120ac
Create Date: 2018-01-16 21:40:59.079693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e7b5f35529'
down_revision = '8a165b4120ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beauti_essay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(length=1000), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beau_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('beau_photo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beau_photo'], ['beauti_essay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beau_image')
    op.drop_table('beauti_essay')
    # ### end Alembic commands ###
