"""empty message

Revision ID: c464497268ad
Revises: 6297398412ed
Create Date: 2018-01-12 11:17:12.666666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c464497268ad'
down_revision = '6297398412ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'count')
    # ### end Alembic commands ###
