"""empty message

Revision ID: e06db92a386d
Revises: c464497268ad
Create Date: 2018-01-12 16:48:49.743884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06db92a386d'
down_revision = 'c464497268ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('praise_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'praise_num')
    # ### end Alembic commands ###
