"""empty message

Revision ID: f29f0e4bc4f9
Revises: 2f075959b3b2
Create Date: 2018-01-16 22:25:13.909865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29f0e4bc4f9'
down_revision = '2f075959b3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('be_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('be_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['be_id'], ['beauti_essay.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('be_user')
    # ### end Alembic commands ###
